services:
  es01:
    container_name: ragflow-es-01
    image: elasticsearch:8.11.4
    volumes:
      - ./volumes/es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=rag_flow
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - cluster.max_shards_per_node=4096
      - TZ=Asia/Shanghai
    mem_limit: 8073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - ragflow
#    healthcheck:
#      test: ["CMD-SHELL", "curl http://localhost:9200"]
#      interval: 10s
#      timeout: 10s
#      retries: 120
#    restart: always

  mysql:
    image: mysql:5.7.18
    container_name: ragflow-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/var/lib/mysql
      - ./init_data/mysql/init.sql:/data/application/init.sql
    networks:
      - ragflow
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
#    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: ragflow-minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=rag_flow
      - MINIO_ROOT_PASSWORD=infini_rag_flow
      - TZ=Asia/Shanghai
    volumes:
      - ./volumes/minio/data:/data
    networks:
      - ragflow
#    restart: always

  redis:
    image: redis:7.2.4
    container_name: ragflow-redis
    command: redis-server --requirepass infini_rag_flow --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ragflow
#    restart: always

  frontend:
    image: nginx:1.24.0
    container_name: ragflow-frontend
    environment:
      - SERVER_HOST=http://192.168.1.7:9380
      - TZ=Asia/Shanghai
    volumes:
      - ./init_data/dist:/ragflow/web/dist
#      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./init_data/nginx/ragflow.conf.template:/etc/nginx/conf.d/ragflow.conf.template
      - ./init_data/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./init_data/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: [ "sh", "-c", "envsubst '$$SERVER_HOST' < /etc/nginx/conf.d/ragflow.conf.template > /etc/nginx/conf.d/ragflow.conf && nginx -g 'daemon off;'" ]
    ports:
      - 9381:80
    networks:
      - ragflow


networks:
  ragflow:
    driver: bridge
